Attempt to fix foreign key conflicts in mysql and postgres
mysql
```
InternalError: (1701, u'Cannot truncate a table referenced in a foreign
key constraint (`sahana`.`event_config`, CONSTRAINT
`event_config_ibfk_2` FOREIGN KEY (`config_id`) REFERENCES
`sahana`.`gis_config` (`id`))')
```

postgres
```
NotSupportedError: cannot truncate a table referenced in a foreign key
constraint
DETAIL: Table "gis_menu" references "gis_config". HINT:
Truncate table "gis_menu" at the same time, or use TRUNCATE ... CASCADE.
```