Display error in map component if there is no GIS config (#1516)
* Display error in map component if there is no GIS config

Displaying the error in the map component allows the rest of the webpage
to load normally and removes an unsafe redirect from a lower level
function, as suggested in #1513.

This commit also moves the instantiation of the loader component into
the `_setup()` method after we've fetched the config, to ensure that the
error message doesn't appear with a permanent loading icon above it.

* Attempt to fix foreign key conflicts in mysql and postgres

mysql
```
InternalError: (1701, u'Cannot truncate a table referenced in a foreign
key constraint (`sahana`.`event_config`, CONSTRAINT
`event_config_ibfk_2` FOREIGN KEY (`config_id`) REFERENCES
`sahana`.`gis_config` (`id`))')
```

postgres
```
NotSupportedError: cannot truncate a table referenced in a foreign key
constraint
DETAIL: Table "gis_menu" references "gis_config". HINT:
Truncate table "gis_menu" at the same time, or use TRUNCATE ... CASCADE.
```

* Use dummy function in test instead of removing config

* Update error styling

- Give css class minimal red border
- Remove use of T
- Switch back to using A() now that it's not inside a translation

* Update MAP2 error message to match

* Mock out get_config() on class instead of instance

* Bind get_config as a staticmethod in more places

It needs to be bound when we assign it to the test class so that it properly
gets re-bound when we re-assign it as a staticmethod on GIS during teardown.

* Specify bytes for py2/3 compatibility